#!/usr/bin/env bash
# Regenerates every platform's app icon from tool/icon/foreground.svg (`make icon`).
# Needs rsvg-convert and ImageMagick (brew install librsvg imagemagick).
set -euo pipefail
cd "$(dirname "$0")/.."

SVG=tool/icon/foreground.svg
RED='#dc0a2d'
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Full icon: red rounded square with the art zoomed so it fills ~85% of it.
rsvg-convert -w 1400 -h 1400 "$SVG" -o "$TMP/fg.png"
magick -size 1024x1024 xc:none -fill "$RED" -draw "roundrectangle 0,0 1023,1023 220,220" \
  \( "$TMP/fg.png" -gravity center -crop 1024x1024+0+0 +repage \) \
  -gravity center -composite "$TMP/full.png"

# Android: legacy launcher PNGs plus an adaptive icon (API 26+): red background
# colour + transparent foreground, which launchers mask into their own shape.
RES=android/app/src/main/res
for pair in mdpi:48 hdpi:72 xhdpi:96 xxhdpi:144 xxxhdpi:192; do
  d=${pair%%:*}; s=${pair##*:}
  magick "$TMP/full.png" -resize "${s}x${s}" "$RES/mipmap-$d/ic_launcher.png"
  fs=$((s * 108 / 48))
  rsvg-convert -w "$fs" -h "$fs" "$SVG" -o "$RES/mipmap-$d/ic_launcher_foreground.png"
done
mkdir -p "$RES/mipmap-anydpi-v26"
cat > "$RES/mipmap-anydpi-v26/ic_launcher.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/icon.sh -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
EOF
cat > "$RES/values/ic_launcher_background.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/icon.sh -->
<resources>
    <color name="ic_launcher_background">$RED</color>
</resources>
EOF

# Windows: multi-size .ico embedded in the exe.
magick "$TMP/full.png" -define icon:auto-resize=256,64,48,32,16 windows/runner/resources/app_icon.ico

# Linux: window icon, installed next to the binary's data/ by linux/CMakeLists.txt.
magick "$TMP/full.png" -resize 256x256 linux/runner/resources/app_icon.png

echo "icon: regenerated Android, Windows and Linux icons from $SVG"
